packages:
  - packages/*
  - apps/*
catalogs:
  dev:
    "@jobinjia/eslint-config": ^0.0.5
    "@types/node": ^22.17.0
    "@unocss/cli": ^66.4.1
    "@unocss/reset": ^66.4.1
    "@unocss/vite": ^66.4.1
    "@vitejs/plugin-vue": ^6.0.1
    "@vitejs/plugin-vue-jsx": ^5.0.1
    "@vue/test-utils": ^2.4.6
    ansis: ^4.1.0
    bumpp: ^10.2.2
    eslint: ^9.32.0
    eslint-plugin-oxlint: ^1.11.0
    happy-dom: ^18.0.1
    husky: ^9.1.7
    lint-staged: ^16.1.4
    npm-run-all: ^4.1.5
    oxlint: ^1.11.0
    rolldown: 1.0.0-beta.24
    tinyglobby: ^0.2.14
    tsdown: ^0.12.9
    typescript: ^5.9.2
    unocss: ^66.4.1
    unplugin-vue: ^6.2.0
    vite: npm:rolldown-vite@latest
    vitest: ^3.2.4
    vue: ^3.5.18
    vue-tsc: ^3.0.5
